repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'f35773e46d096de5c45365f1a47eeeef36fc83ed'
    hooks:
    - id: isort
