language: python

# Setup for python 3.6
python: "3.6"

install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt

script:
    - pytest --cov=thegame
    - black . --check
    - isort -rc --check .

after_success:
    - codecov

